# name: Generate Sponsors README
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout 🛎️
#         uses: actions/checkout@v2

#       - name: Generate Sponsors 💖
#         uses: JamesIves/github-sponsors-readme-action@1.0.5
#         with:
#           token: ${{ secrets.SECRET_WITH_SPONSORS_ACCESS }}
#           file: 'README.md'
#           # minimum: 2500

#       - name: Deploy to GitHub Pages 🚀
#         uses: JamesIves/github-pages-deploy-action@4.1.1
#         with:
#           branch: main
#           folder: '.'

#       - name: Setup npm
#         run: npm ci

#       - name: Update Commands
#         run: node .github/workflows/updateWiki.js

#       - name: Push Changes to Repo
#         run: git add .; git commit -m "updated commands page on wiki"; git push origin main

#       - name: Push Wiki Changes
#         uses: Andrew-Chen-Wang/github-wiki-action@v2
#         env:
#           # Make sure you have that / at the end. We use rsync
#           # WIKI_DIR's default is wiki/
#           WIKI_DIR: wiki/
#           GH_TOKEN: ${{ secrets.SECRET_WITH_REPO_ACCESS }}
#           GH_MAIL: ${{ secrets.WIKI_EMAIL }}
#           GH_NAME: ${{ github.repository_owner }}
#           EXCLUDED_FILES: "a/ b.md"
